define({
    'title': {
        'orders': 'Orders',
		'language': 'Language',
		'settings': 'Settings',
		'customer': 'Customer',
		'customers': 'Customers',
		'selectCustomer': 'Select Customer',
		'map': 'Map',
		'viewAttachment': 'View Attachment',
		'addItem': 'Add Item',
		'uploadAttachment': 'Upload Attachment',
		'searchProducts': 'Search Products',
		'orderDetailsReport': 'Order Details Report',
		'orderStatusReport': 'Order Status Report',
		'stockOnHand': 'Stock On Hand',
		'stockItemFind': 'Stock Item Find',
		'reports': 'Reports',
		'today': 'Today',
		'yesterday': 'Yesterday',
		'earlier': 'Earlier'
    },
	'label': {
		'orderNumber': 'Order Number',
		'customerOrderNumber': 'Customer Order Number',
		'customer': 'Customer',
		'siteID_': 'Site ID *',
		'shipVia____': 'Ship Via *  ',
		'shipTo__': 'Ship To *',
		'orderDate': 'Order Date',
		'remarks': 'Remarks',
		'createdDate': 'Created Date',
		'referenceNumber': 'Reference Number',
		'description': 'Description',
		'attachment': 'Attachment',
		'inventoryID': 'Inventory ID',
		'inventoryDescr': 'Inventory Descr',
		'inventoryPrice': 'Inventory Price',
		'inventoryQuantityAvailable': 'Inventory Quantity Available',
		'price__': 'Price *',
		'quantity__': 'Quantity *',
		'stockItemDescription___': 'Stock Item Description * ',
		'siteID____': 'Site ID *  '
	},
    'button': {
        'logIn': 'Log In',
		'oK': 'OK',
		'yes_No': 'Yes,No'
    },
    'input': {
        'username': 'Username',
        'password': 'Password',
		'typeKeywordToSearch': 'Type keyword to search',
		'checkingUser': 'Checking user...',
		'stockItemDescription': 'Stock Item Description'
    },
	'text': {
		'default': 'Default',
		'price___': 'Price : ',
		'qty___': 'Qty : ',
		'empty': 'Empty',
		'qty__': 'Qty :',
		'price__': 'Price :',
		'orderNo__': 'Order No: ',
		'custOrderNo__': 'Cust Order No: ',
		'postedOn_': 'Posted on ',
		'shipTo____': 'Ship To :  ',
		'date__': 'Date :',
		'status___': 'Status : ',
		'qtyAvailable': 'Qty Available',
		'qtyOnHand': 'Qty On Hand',
		'next_': 'Next '
	},
	'li': {
		'menu': 'Menu',
		'orders': 'Orders',
		'customers': 'Customers',
		'reports': 'Reports',
		'language': 'Language',
		'signOut': 'Sign out',
		'details': 'Details',
        'items': 'Items',
        'attachment': 'Attachment',
		'viewMap': 'View Map',
		'contact': 'Contact',
		'creditCheck': 'Credit Check',
		'totalOutstanding': 'Total Outstanding',
		'language': 'Language',
		'viewAttachment': 'View Attachment',
		'uploadFile': 'Upload File',
		'filter': 'Filter',
		'new': 'New',
		'all': 'All',
		'drafts': 'Drafts',
		'sent': 'Sent',
		'deleted': 'Deleted',
		'pleaseWait': 'Please wait',
		'takePicture': 'Take Picture',
		'selectPictureFromLibrary': 'Select Picture from Library',
		'uploadPicture': 'Upload Picture',
		'image': 'Image',
		'orderDetails': 'Order Details',
		'orderDetailsForOrder': 'Order Details For Order',
		'oWOrderNo___': 'OW Order No : ',
		'cust_OrderNo__': 'Cust. Order No :',
		'orderTotal': 'Order Total',
		'qty___': 'Qty : ',
		'orderStatus': 'Order Status',
		'inventoryID___': 'Inventory ID : ',
		'description__': 'Description :',
		'site__': 'Site :',
		'selectReport': 'Select Report',
		'stockOnHand': 'Stock On Hand'
	},
    'checkBox': {
        'rememberMe': 'Remember Me'
    },
	'message': {
		'accountExceedCreditLimit': 'Account exceed credit limit.',
		'error': 'Error',
		'pleaseProvideAValidUsernameAndPassword_': 'Please provide a valid username and password.',
		'youMustEnterAPrice': 'You must enter a price',
		'youMustEnterAQuantity': 'You must enter a quantity',
		'quantityCannotBe0': 'Quantity cannot be 0',
		'anErrorOccurredWhileTryingToSaveThisItem': 'An error occurred while trying to save this item',
		'anErrorOccurredWhileTryingToUpdateThisItem': 'An error occurred while trying to update this item',
		'doYouWantToDeleteThisItem_': 'Do you want to delete this item?',
		'deleteOrder': 'Delete Order',
		'anErrorOccurredWhileTryingToDeleteThisItem': 'An error occurred while trying to delete this item',
		'errorGettingPicture__X': 'Error getting picture: %1s',
		'uploadSuccessful__X_BytesUploaded_': 'Upload successful: %1d bytes uploaded.',
		'success': 'Success',
		'uploadFailed__Code___X___Y___Z': 'Upload failed: Code = %1s.  %2s.  %3s',
		'takePictureFirst_': 'Take picture first.',
		'exceptionInUpload__X': 'Exception in upload: %1s',
		'doYouWantToDeleteThisOrder_': 'Do you want to delete this order?',
		'doYouWantToSubmitThisOrder_': 'Do you want to submit this order?',
		'submitOrder': 'Submit Order',
		'doYouWantToSaveYourChanges_': 'Do you want to save your changes?',
		'saveChanges': 'Save Changes',
		'siteIDCannotBeEmpty': 'Site ID cannot be empty',
		'shipToCannotBeEmpty': 'Ship To cannot be empty',
		'itemCannotBeEmpty': 'Item cannot be empty',
		'orderSavedSuccessfully': 'Order saved successfully',
		'anErrorOccurredWhileTryingToUpdateThisOrder': 'An error occurred while trying to update this order',
		'pleaseEnterTheCustomerOrderNumber': 'Please enter the customer order number',
		'pleaseSelectTheCustomerAndSiteID__CustomerCannotBeEmpty': 'Please select the customer and site ID. Customer cannot be empty',
		'pleaseSelectSiteID_': 'Please select site ID.',
		'pleaseSelectTheCustomer__CustomerCannotBeEmpty': 'Please select the customer. Customer cannot be empty',
		'anErrorOccurredWhileTryingToDeleteThisOrder': 'An error occurred while trying to delete this order',
		'pleaseEnterTheReferenceOrderNumber': 'Please enter the reference order number',
		'stockCannotBeEmpty': 'Stock cannot be empty'
	},
	'time': {
		// 'orderFormat': 'YYYY-MM-DD HH:mm:ss'
	},
	'language': {
        'vietnamese': 'VIETNAMESE',
        'english': 'ENGLISH',
        'france': 'FRANCE',
        'japanese': 'JAPANESE',
        'turkey': 'TURKEY'
	}
});