define({
'title': {
'orders': 'Đơn đặt hàng',
'language': 'Ngôn ngữ',
'settings': 'Cài đặt',
'customer': 'Khách hàng',
'customers': 'Khách hàng',
'selectCustomer': 'Chọn hàng',
'map': 'Bản đồ',
'viewAttachment': 'Xem tập tin đính kèm',
'addItem': 'Bổ sung mục',
'uploadAttachment': 'Tải lên tập tin đính kèm',
'searchProducts': 'Tìm kiếm sản phẩm',
'orderDetailsReport': 'Đặt hàng chi tiết báo cáo',
'orderStatusReport': 'Đặt hàng report',
'stockOnHand': 'Cổ phiếu trên tay',
'stockItemFind': 'Tìm cổ phiếu món',
'reports': 'Báo cáo',
'today': 'Ngày hôm nay',
'yesterday': 'Hôm qua',
'earlier': 'Trước đó '
},
'label': {
'orderNumber': 'Số thứ tự',
'customerOrderNumber': 'Số khách hàng đặt hàng',
'customer': 'Khách hàng',
'siteID_': 'Mã site *',
'shipVia____': 'Ship via *',
'shipTo__': 'Ship tới *',
'orderDate': 'Để ngày',
'remarks': 'Bình luận',
'createdDate': 'Ngày tạo ra',
'referenceNumber': 'Số tham chiếu',
'description': 'Miêu tả',
'attachment': 'File đính kèm',
'inventoryID': 'Mã kho',
'inventoryDescr': 'Hàng tồn kho mô tả',
'inventoryPrice': 'Hàng tồn kho giá',
'inventoryQuantityAvailable': 'Số lượng hàng tồn kho hiện có sẵn',
'price__': 'Giá *',
'quantity__': 'Số lượng *',
'stockItemDescription___': 'Cổ phiếu hàng mô tả *',
'siteID____': 'Trang mã * '
},
'button': {
'logIn': 'Đăng Nhập',
'oK': 'Có',
'yes_No': 'Có không '
},
'input': {
'username': 'Tên đăng nhập',
'password': 'Mật khẩu',
'typeKeywordToSearch': 'Gõ từ khóa để tìm kiếm',
'checkingUser': 'Kiểm tra người sử dụng ...',
'stockItemDescription': 'Cổ phiếu hàng mô tả '
},
'text': {
'default': 'Mặc định',
'price___': 'Giá:',
'qty___': 'Số lượng:',
'empty': 'Trống',
'qty__': 'Số lượng:',
'price__': 'Giá:',
'orderNo__': 'Số thứ tự:',
'custOrderNo__': 'Số thứ tự khách hàng:',
'postedOn_': 'Đăng trên',
'shipTo____': 'Gửi đến : ',
'date__': 'Ngày:',
'status___': 'Tình trạng: ',
'qtyAvailable': 'Số lượng có sẵn',
'qtyOnHand': 'Số lượng trên tay',
'next_': 'Kế tiếp '
},
'li': {
'menu': 'Thực đơn',
'orders': 'Đơn đặt hàng',
'customers': 'Khách hàng',
'reports': 'Báo cáo',
'language': 'Ngôn ngữ',
'signOut': 'Đăng xuất',
'details': 'Chi tiết',
'items': 'Mặt hàng',
'attachment': 'Tập tin đính kèm',
'viewMap': 'Xem bản đồ',
'contact': 'Tiếp xúc',
'creditCheck': 'Kiểm tra tín dụng',
'totalOutstanding': 'Tổng số nổi bật',
'language': 'Ngôn ngữ',
'viewAttachment': 'Xem tập tin đính kèm',
'uploadFile': 'Gửi lên file',
'filter': 'Lọc',
'new': 'Mới',
'all': 'Tất cả',
'drafts': 'Nháp',
'sent': 'Gởi',
'deleted': 'Đã bị xóa',
'pleaseWait': 'Xin vui lòng chờ',
'takePicture': 'Chụp ảnh',
'selectPictureFromLibrary': 'Chọn ảnh từ thư viện',
'uploadPicture': 'Tải lên ảnh',
'image': 'Hình ảnh',
'orderDetails': 'Đặt hàng Chi tiết',
'orderDetailsForOrder': 'Đặt hàng Chi tiết Đối với thứ tự',
'oWOrderNo___': 'Số thứ tự OW:',
'cust_OrderNo__': 'Số thứ tự khách hàng:',
'orderTotal': 'Đặt hàng Tổng số',
'qty___': 'Số lượng:',
'orderStatus': 'Tình trạng đơn hàng',
'inventoryID___': 'Mã hàng tồn kho:',
'description__': 'Mô tả:',
'site__': 'Vị trí:',
'selectReport': 'Chọn báo cáo',
'stockOnHand': 'Cổ trên tay '
},
'checkBox': {
'rememberMe': 'Ghi nhớ '
},
'message': {
'accountExceedCreditLimit': 'Tài khoản vượt quá hạn mức tín dụng.',
'error': 'Lỗi',
'pleaseProvideAValidUsernameAndPassword_': 'Vui lòng cung cấp tên người dùng và mật khẩu hợp lệ.',
'youMustEnterAPrice': 'Bạn phải nhập một giá',
'youMustEnterAQuantity': 'Bạn phải nhập số lượng',
'quantityCannotBe0': 'Số lượng không thể là 0',
'anErrorOccurredWhileTryingToSaveThisItem': 'Đã xảy ra lỗi trong khi cố gắng để lưu mục này',
'anErrorOccurredWhileTryingToUpdateThisItem': 'Đã xảy ra lỗi trong khi cố gắng để cập nhật mục này',
'doYouWantToDeleteThisItem_': 'Bạn muốn xóa ảnh này?',
'deleteOrder': 'Xóa đặt hàng',
'anErrorOccurredWhileTryingToDeleteThisItem': 'Đã xảy ra lỗi trong khi cố gắng để xóa mục này',
'errorGettingPicture__X': 'Lỗi nhận hình ảnh:%1s',
'uploadSuccessful__X_BytesUploaded_': 'Tải lên thành công:%1s bytes đã tải lên.',
'success': 'Thành công',
'uploadFailed__Code___X___Y___Z': 'Tải lên không thành: Code =%1s %2s %3s..',
'takePictureFirst_': 'Hãy hình ảnh đầu tiên.',
'exceptionInUpload__X': 'Ngoại lệ trong upload:%1s',
'doYouWantToDeleteThisOrder_': 'Bạn có muốn xóa đơn này?',
'doYouWantToSubmitThisOrder_': 'Bạn có muốn nộp đơn đặt hàng này?',
'submitOrder': 'Gửi đặt hàng',
'doYouWantToSaveYourChanges_': 'Bạn có muốn lưu các thay đổi của bạn?',
'saveChanges': 'Lưu thay đổi',
'siteIDCannotBeEmpty': 'Mã trang web không thể để trống',
'shipToCannotBeEmpty': 'Gửi tới không thể để trống',
'itemCannotBeEmpty': 'Món hàng không thể để trống',
'orderSavedSuccessfully': 'Để lưu thành công',
'anErrorOccurredWhileTryingToUpdateThisOrder': 'Đã xảy ra lỗi khi cố gắng cập nhật tự này',
'pleaseEnterTheCustomerOrderNumber': 'Vui lòng nhập số lượng đơn đặt hàng',
'pleaseSelectTheCustomerAndSiteID__CustomerCannotBeEmpty': 'Vui lòng chọn các khách hàng và mã trang web. Khách hàng không thể để trống',
'pleaseSelectSiteID_': 'Vui lòng chọn mã trang web.',
'pleaseSelectTheCustomer__CustomerCannotBeEmpty': 'Hãy lựa chọn cho khách hàng. Khách hàng không thể để trống',
'anErrorOccurredWhileTryingToDeleteThisOrder': 'Đã xảy ra lỗi trong khi cố gắng để xóa lệnh này',
'pleaseEnterTheReferenceOrderNumber': 'Vui lòng nhập số thứ tự tài liệu tham khảo',
'stockCannotBeEmpty': 'Cổ phiếu không thể để trống '
},
'time': {
// 'orderFormat': 'YYYY-MM-DD HH: mm: ss '
},
'language': {
'vietnamese': 'VIỆT',
'english': 'ANH',
'france': 'PHÁP',
'japanese': 'NHẬT BẢN',
'turkey': 'THỔ NHĨ KỲ'
}
});
